### ISSUE TITLE
Making TagView Right To Left

### ISSUE THREAD

**Issue by doorbash** [kaedea/Android-Cloud-TagView-Plus#5]
Hi,Tnx for your great work Kaedea.
I'm going to make TagView right to left since in my country Iran the language (Persian) is right to left.
I mean I need the tags to be set from right and another tag that will be added later set to left of it.
How can I do that?
Can you develop the code and add this option to it please?

**Comment by amirghm** [comment]
I myself try to change the library, (for example change gravity and change rule of Right_Of to Left_Of) but no luck! After assigning this change, the tags will drawn erroneously and in some cases draw in front of previous tag.

please provide a way

thanks a lot

**Comment by kaedea** [comment]
Would you please offer me a  sreenshot?
Okay, I am now upgrading this project, fixing some bugs and adjust it into a gradle project. It may take some time because I am coming into beasy season with my job. 
You can show me some image about the problem via kidhaibara@gmail.com

**Comment by kaedea** [comment]
to mi1s0n
So you want to show Tag in and right-to-left order? Like:
add TagA;
add TagB;
add TagC;
but show " TagC TagB TagA "?

**Comment by amirghm** [comment]
no let me I describe what we want (me and milson is friends).

in Persian, our language start from right to left. so all of our layout should start from right to left.
but in English and default android, layouts start from left to right.
I and milson try to customize this library to achieve this, but can't.

you can see in this image what we want:
http://i.imgur.com/Thlfvf8.png

we want the layout starts from right to left not left to right

**Comment by amirghm** [comment]
wow! I've solve it!! 
I assign TagView ScaleY = -1 and item_tagview linearlayout container ScaleY= -1.
this is silly work but a powerful way to solve this issue!!
thank you again :)
